CC = g++
CFLAGS = -g -std=c++11 -Wall -O3

all:
	$(CC) $(CFLAGS) -o Main Main.cpp TupleGenerator.cpp Independent_Partitioning_Algorithm.cpp Concurrent_Partitioning_Algorithm.cpp

clean:
	  $(RM) TupleGenerator.o Concurrent_Partitioning_Algorithm.o Independent_Partitioning_Algorithm.o Main.o Main
